service: quiccasa-service
# app and org for use with dashboard.serverless.com
app: quiccasa-service
#org: sistemisolari.com

# only deploy with a specific Serverless version
frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverless
  stage: dev
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    apiGateway: true
    lambda: true

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
          Resource: { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref": "ServerlessDeploymentBucket" }, "/*" ] ] }

# service wide environment variables
#environment:
#  variable1: value1

# packaging information
package:
  patterns:
    - '!private/**'
    - '!tmp/**'
    - '!node_modules/**'

functions:
  unsubscribe:
    handler: api.unsubscribe
    memorySize: 128 # MB, default is 1024 MB
    timeout: 10 # seconds, default is 6 seconds
    description: Unsubscribe user from service subscription
    events:
      - http: 
          method: get
          path: unsubscribe

# CloudFormation resource templates
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
