#!/usr/bin/env bash
#
# Create an RDS database via aws

DB_NAME="quiccasa"
DB_USER="admin"
DB_PASSWORD="c_8G6+Q3xxLp8"

aws rds create-db-instance --db-name "$DB_NAME" --engine MySQL \
--db-instance-identifier MySQLForLambdaTest --backup-retention-period 3 \
--db-instance-class db.t2.micro --allocated-storage 5 --no-publicly-accessible \
--master-username "$DB_USER" --master-user-password "$DB_PASSWORD"
